# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('employ_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата приема')),
                ('unemploy_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер')),
                ('document_type', models.IntegerField(choices=[(0, 'Прием на работу'), (1, 'Увольнение')], verbose_name='Система доставки')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Должность')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание (не обязательно)')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('employ_date', models.DateField(blank=True, null=True, verbose_name='Дата приема')),
                ('unemploy_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrdep.Post', verbose_name='Должность')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrdep.Staff'),
        ),
    ]
