# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrdep', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='unemploy_date',
            new_name='dismiss_date',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='unemploy_date',
            new_name='dismiss_date',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.IntegerField(choices=[(0, 'Прием на работу'), (1, 'Увольнение')], verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrdep.Staff', verbose_name='Сотрудник'),
        ),
    ]
