# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdep', '0003_auto_20160518_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='dismiss_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AlterField(
            model_name='document',
            name='employ_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема'),
        ),
    ]
