# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrdep', '0006_auto_20160518_1304'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set([('date', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together=set([('first_name', 'middle_name', 'last_name')]),
        ),
    ]
