# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrdep', '0008_auto_20160519_1136'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set([('staff', 'document_type', 'employ_date', 'dismiss_date')]),
        ),
    ]
